### ISSUE TITLE
[iOS] Issue in Podspec

### ISSUE THREAD

**Issue by kimthompson** [birdofpreyru/react-native-fs#13]
Thank you very much for taking over this library! We have also been running into difficulties with `react-native-fs`, and I very much look forward to having a more stable experience soon.

I tried to install `@dr.pogodin/react-native-fs` into our React Native 0.69.12 project but had issues getting the app running on iOS. It seems to install all of the packages and pods just fine, but it runs into trouble when I try to run it on a simulator or physical device with the command `react-native run-ios`. I've pasted the final part of the output with a few details omitted in curly brackets below.

```
The following build commands failed:
        CompileC /Users/{username}/Library/Developer/Xcode/DerivedData/{app_name+hash}/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/dr-pogodin-react-native-fs.build/Objects-normal/arm64/ReactNativeFs.o /Users/{username}/Git/{project_dir}/node_modules/@dr.pogodin/react-native-fs/ios/ReactNativeFs.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'dr-pogodin-react-native-fs' from project 'Pods')
(1 failure)
```

I've tried all the usual cleaning and restarting methods to make sure it's not just me. Do you know what might be causing this?

Let me know if there's anything I can do to help, and thanks again for taking this on!

**Comment by birdofpreyru** [comment]
Hey @kimthompson , most probably RN v0.69 causes it; that's why peer dependency on RN is declared as v0.72. FYI, RN itself [considers the latest 3 minor versions as actively maintained](https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported), thus v0.69 is not supported anymore by their policy. And as far as this library is concerned, my current plan is at any moment to maintain the latest RN release only &mdash; unless somebody funds maintenance for the older versions :)

**Comment by kimthompson** [comment]
Thanks for responding so quickly! Apologies that I missed that.
