### ISSUE TITLE
Background Downloads Tutorial (iOS) Not Working

### ISSUE THREAD

**Issue by relaxxpls** [birdofpreyru/react-native-fs#27]
The documentation [here](https://github.com/birdofpreyru/react-native-fs#background-downloads-tutorial-ios) seems to be outdated.

I have tried using the following code
```objc
#import <ReactNativeFs.h>

- (void)application:(UIApplication *)application handleEventsForBackgroundURLSession:(NSString *)identifier completionHandler:(void (^)())completionHandler
{
  [ReactNativeFs setCompletionHandlerForIdentifier:identifier completionHandler:completionHandler];
}
```

This fails aswell due to
```
No known class method for selector 'setCompletionHandlerForIdentifier:completionHandler:'
```

@birdofpreyru Are any additional steps needed for iOS?

**Comment by birdofpreyru** [comment]
The &laquo;Background downloads&raquo; feature is fixed in [v2.23.0](https://github.com/birdofpreyru/react-native-fs/releases/tag/v2.23.0) (requires minor changes in the host app code), and it is tested and works for me in [the Example App](https://github.com/birdofpreyru/react-native-fs/blob/3849493cd23ce8d18bfcb886ec44ff9bb53fa32b/example/src/TestBaseMethods.tsx#L330-L379). That does not mean there is no other problems with [downloadFile()](https://github.com/birdofpreyru/react-native-fs?tab=readme-ov-file#downloadfile) (_i.e._ #24) &mdash; I haven't looked deeper into that one.
