### ISSUE TITLE
The package doesn't seem to be linked

### ISSUE THREAD

**Issue by StefanoCremonaOneAsg** [birdofpreyru/react-native-fs#41]
Trying to link your fork in an existing project coming from the original react-native-fs.

I initially have several "Syntax Error" importing some types, but once I fix all of them, I have 
"The package doesn't seem to be linked".

Building for iOS, 
XCode 15.3 (15E204a)

"react": "17.0.1",
"react-native": "0.64.4",
"@dr.pogodin/react-native-fs": "2.25.0",
"typescript": "3.8.3",
node: 16.14.2
npm: 8.5.0
react-native-cli 2.0.1

Any help is welcome
Thank you

![Screenshot 2024-05-09 at 12 07 11](https://github.com/birdofpreyru/react-native-fs/assets/127495946/fd1369a9-c525-4985-9c32-9c6cb1c00967)
![Screenshot 2024-05-09 at 12 09 14](https://github.com/birdofpreyru/react-native-fs/assets/127495946/80d39a55-30d7-4ed3-801f-053ebc2bb218)

**Comment by birdofpreyru** [comment]
Hey @StefanoCremonaOneAsg ,

Your problem is `"react-native": "0.64.4"` &mdash; I aim to keep my fork compatible with the latest RN version (currently &mdash; v0.74), and it is probably backward compatible to a few older minor versions of RN (but I have no financial capacity to invest into testing / ensuring it). RN v0.64.4 is heavily outdated ([RN considers unmaintained everything prior to v0.70](https://reactnative.dev/versions)), for that you perhaps stick to the upstream library, or upgrade your app to modern RN.
