### ISSUE TITLE
[iOS] stat / hash function cannot resolve bookmark:// path.

### ISSUE THREAD

**Issue by leo6104** [birdofpreyru/react-native-fs#75]
### Current implementation
```
  NSURL *url = [ReactNativeFs pathToUrl:filepath error:&error];
  if (error) return [[RNFSException fromError:error] reject:reject];

  BOOL allowed = [url startAccessingSecurityScopedResource];

  @try {
    BOOL fileExists = [[NSFileManager defaultManager] fileExistsAtPath:filepath];
```

### Current Behavior 
ENOENT: no such file or directory, open 'bookmark://...'

### Expect Implementation
```
  NSURL *url = [ReactNativeFs pathToUrl:filepath error:&error];
  if (error) return [[RNFSException fromError:error] reject:reject];

  BOOL allowed = [url startAccessingSecurityScopedResource];

  @try {
    NSString *resolvedPath = [url path];
    BOOL fileExists = [[NSFileManager defaultManager] fileExistsAtPath:resolvedPath];
```

**Comment by birdofpreyru** [comment]
Fixed in [v2.29.0](https://github.com/birdofpreyru/react-native-fs/releases/tag/v2.29.0).

FYI, it was a notch more difficult then just getting and using `url.path`, instead entire method implementations had to be re-written using functions operating on the `url` instances, rather than string paths. Thus, keep an eye for possible regressions.
